Row {}
-------------------------------------

### {data-width=200}

```{r } 
flexdashboard::valueBox(mLIBVER, icon="fa-folder-open-o", href="https://www.oecd-nea.org", color=as.character(my_colors[mLIBVER]), caption = paste(" Released in ", libdates[mLIBVER]))

```   

### {data-width=160}

```{r } 
flexdashboard::valueBox(mSYMAM, color="Gainsboro", caption = "Neutron File",  
                        href="#map"
                        )

```   

### {data-width=128}

```{r } 
flexdashboard::valueBox(tot, color="Gainsboro", caption = "Sections in file")

```   

### {data-width=128}

```{r } 
flexdashboard::valueBox(totalupdated, color=UpdatedColor, caption = "Updated",
                        icon="fa-chevron-up")

```   

### {data-width=128}

```{r } 
flexdashboard::valueBox(newinlib1, color=NewColor, caption = "New", 
                        icon="fa-chevron-up")

```   

### {data-width=128}

```{r } 
flexdashboard::valueBox(totunchanged, color="LightGray", caption = "Unchanged")

```   

### {data-width=128}

```{r } 
flexdashboard::valueBox(erasedfromlib2, color=ErasedColor, caption = "Erased", 
                        icon="fa-chevron-down")

```   

Row {}
-------------------------------------


