---
title: "Nuclear Data Library Breakdown"
author: "Luca Fiorito & Franco Michel-Sendis"
# date: "9 February 2018"
# always_allow_html: yes
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
  # pdf_document: default
params:
  RELEASE: "JEFF-3.3"
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE)
```

```{r source, include=FALSE, cache = TRUE}
source('global.R')
my_colors <- c(
  "JEFF-3.3"="#097C28",
  "JEFF-3.2"="#72FD7A",
  "JEFF-3.1.2"="#2CA743",
  "JEFF-3.1.1"="#3DBC51",
  "JEFF-3.1"="#4FD25E",
  "JEFF-3.0"="#60E76C",
  "JEFF-2.2"="#46f0f0",
  "JENDL-4.0"="#ff1493",
  "JENDL-3.3"="#ffc0cb",
  "JENDL-3.2"="#ffb6c1",
  "ENDFB-8.0"="#FFC129",
  "ENDFB-7.1"="#FADB32",
  "ENDFB-7.0"="#F5F63C",
  "ENDFB-6.8"="#F4F50A",
  "TENDL-2017"="#aa6e28",
  "TENDL-2016"="#fffac8",
  "TENDL-2015"="#800000",
  "TENDL-2014"="#aaffc3",
  "TENDL-2013"="#808000",
  "TENDL-2012"="#ffd8b1",
  "TENDL-2011"="#000080",
  "TENDL-2010"="#808080",
  "TENDL-2009"="#000000"
  )
```

```{r filter, include=FALSE}
C <- plyr::count(df[df$LIBVER==params$RELEASE,], 'LIBVERORIG')
C <- transform(C, percent = scales::percent(freq / sum(freq)))
C <- C[rev(order(C$LIBVERORIG)),]
```

# `r params$RELEASE`

Row {data-height=200}
-------------------------------------

### Description

MF/MT breakdown of the **`r strsplit(params$RELEASE, "-")[[1]][1]`** library, version **`r strsplit(params$RELEASE, "-")[[1]][2]`**.

Each slide of the <span style="color:blue">pie chart</span> represents the amount of MF/MT sections (in percent) that originates from a given nuclear data library release.

The same information is reported in the <span style="color:blue">table</span> in absolute (**COUNT**) and percent (**PERCENT**) values.

> **Example:** `r max(C$freq)` MF/MT sections of `r params$RELEASE` are taken from `r C[which.max(C$freq),]$LIBVERORIG`

Row {data-height=800}
-------------------------------------

### Pie Chart
```{r piechart}
library(ggplot2)
midpoint <- cumsum(C$freq) - C$freq/2
Pie_Chart <- ggplot(C, aes(x=1,y=freq, fill=LIBVERORIG)) +
  geom_bar(stat="identity") +
  coord_polar(theta='y') +
  scale_fill_manual(values=my_colors) +
  labs(fill="LIBRARY", y="", x="") +
  scale_y_continuous(breaks=midpoint, labels=C$percent) +
  theme_light() +
  theme(plot.title=element_text(size=20, vjust=1),
        plot.background=element_rect(fill="white"),
        axis.ticks=element_blank(),
        axis.title=element_blank(),
        axis.text.y=element_blank(),
        axis.text.x=element_text(color='black',size=12),
        plot.margin = unit(c(0.7, 0, 2, 1), "cm")) #top, right, bottom, left
print(Pie_Chart)
```


### Table
```{r table}
C %>% DT::datatable(rownames=FALSE,
                    colnames=c("LIBRARY","COUNT","PERCENT"),
                    options = list(
                      autowidth = TRUE,
                      order = list(1, 'desc'),
                      pageLength = 100,
                      columnDefs = list(list(className = 'dt-center', targets = 1:2)),
                      sDom="rt")
                    )
```

