---
title: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme : sandstone #readable #spacelab
    logo: ../../www/logo.jpg
    includes:
      #before_body: ../../html/myNEAheader.html
      #after_body: ../../html/myfooter.html
    css: ../../www/styles.css
params:
  SYMAMLIBVER: "U-233-g-JEFF-3.3"
  LIBVER: "JEFF-3.3"
  LIBVER2: "JEFF-3.2" 
  ver: "33"
  
---

 

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)

htmltools::tagList(rmarkdown::html_dependency_font_awesome())

source("../../global.R")

#define parameters to be used here : 
myparams<-strsplit(params$SYMAMLIBVER, "-")[[1]]
 
mX<-myparams[1]
mA<-myparams[2]
mM<-myparams[3]
mLIB<-myparams[4]
mVER<-myparams[5]
mSYMAM<-paste(mX,"-", mA,"-",mM, sep ="")
mLIBVER<-paste(mLIB,"-",mVER, sep = "")

#for use by wrapper.R : 
output_dir<-paste(mLIB,mVER, sep = "")
output_file<-paste(mX,mA,mM)

#for use by datatables :
pdf<-df%>%subset(X==mX & A==mA & M==mM & LIBVER==mLIBVER)
tot<-dim(pdf)[1]

# preparing datatables
pdfo<-df%>%subset(X==mX & A==mA & M==mM)
lib2<-df%>%subset(LIBVER==params$LIBVER, 
                    select = c('MFMT', 'MF', 'MFDES', 'MT', "MTDES", 'LIBVER', 'LIBVERORIG'))
lib1<-pdfo%>%subset(LIBVER==mLIBVER,
                    select = c('MFMT', 'MF', 'MFDES', 'MT', "MTDES", 'LIBVER', 'LIBVERORIG'))
comp<-merge(lib1, lib2, by = c('MFMT', 'MF', 'MFDES', 'MT', "MTDES"), all=TRUE)
data.table::setnames(comp, old=c("LIBVERORIG.x","LIBVERORIG.y"), new=c("LIB1","LIB2"))
data.table::setnames(comp, old=c("MFDES","MTDES"), new=c("MF TYPE","MT TYPE"))
comp<-subset(comp, select = c('MF TYPE', 'MT TYPE', 'MF', 'MT', 'LIB1', 'LIB2'))

#counting : 
# totalfiles<-dim(unique(df%>%subset(LIBVER==params$LIBVER, select=c("X","A","M"))))[1]

totunchanged<-dim(comp%>%subset(LIB1==LIB2))[1]
newinlib<-dim(comp%>%subset(is.na(LIB2)))[1] 

comp[is.na(comp)] <- 'NA'

UpdatedColor <-"Gray"
NewColor <-"Gray"
ErasedColor <-"Gray" 

LIBLINK <-"https://www.oecd-nea.org/dbdata"

lib<-unique(subset(df, LIBVER==mLIBVER, select=c("Z", "X", "A", "M", "SYMAM", "MAT", "LIB")))
totfiles<-dim(lib)[1]

# building columns in lib as html links : 

icon1<-"<i class='fa fa-download'></i>"
icon2<-"<i class='fa fa-sitemap'></i>"
icon3<-"<i class='fa fa-file-alt'></i>"
icon4<-"<i class='fa fa-file></i>"

lib$ENDF6<-paste0(lib$Z,"-",lib$X, "-", lib$A, lib$M,".",tolower(lib$LIB),params$ver)
lib$ENDF6<- paste0("<a href='endf6/",lib$ENDF6,"' target='_blank'>",icon1,"</a>")

lib$ACE<-paste0(lib$Z,"-",lib$X, "-", lib$A,lib$M,".",tolower(lib$LIB),params$ver,"-ACE")
lib$ACE<- paste0("<a href='ace/",lib$ACE,"' target='_blank'>",icon1,"</a>")

lib$MAP<-paste0(lib$X, "-", lib$A,"-", lib$M,".html")
lib$MAP <- paste0("<a href='map/",lib$MAP," ' target='_blank'>",icon2,"</a>")

#adding decay data: 
lib<-merge(x=lib, y=decay, by=c('Z', 'A', 'M'), all.x=TRUE)


# for use by covariance counting :
 
df_cov <-df %>%subset(LIBVER==params$LIBVER & MF %in%(30:40))

nEval<-nrow(unique(subset(df_cov, select="MAT"))) 

breakdown_cov <- df_cov %>% 
  plyr::count('LIBVERORIG') %>% 
  transform(percent = scales::percent(freq / sum(freq)))

breakdown_cov <- breakdown_cov[rev(order(breakdown_cov$LIBVERORIG)),]

```


NDEC
====

```{r child='barheader_libpage.Rmd'}
```

### **Access Files Individually**{data-width=500}

```{r ndec_table}
htmltools::includeHTML("main.html")
```


Row
------


### **List of modified files since previous release `r params$LIBVER2` **{data-width=600}


```{r table_diffs}

lib_diffs <-data.table::fread(paste0(gpath,'JEFF33_vs_JEFF32.csv'))%>%
  subset(MT!=451)%>% 
  dplyr::group_by(MAT) %>% 
  dplyr::summarize(UPDATED=!all(VERORIG==3.2)) %>% merge(mats)  

lib3<-merge(x=lib_diffs, y=lib, all.y=TRUE, by=c('Z','X', 'A', 'MAT','M'))%>%
  subset(select=c('Z', 'SYMAM', 'UPDATED', 'HalfLife', 'MAP'))%>%
  setnames(old=c('Z', 'SYMAM', 'UPDATED', 'HalfLife', 'MAP'),
               new=c('Z', 'Isotope', 'Updated?', 'Half-Life', 'Map'))

datatable(lib3, filter='top', 
          #extensions = 'Buttons', 
          rownames=FALSE, escape=FALSE, 
          options = list(
            pageLength=10,
            autowidth=TRUE, 
            order = list(0, 'asc'),
            columnDefs=list(
              list(width='10%', targets = 0),
              list(className='dt-center', targets = 0:3)
            ))
    )
```
  


```{r}
selected_MF <- 31
```


MF`r selected_MF`
=====================================
```{r}
df_cov <- df %>%
  subset(LIBVER==params$LIBVER & MF==selected_MF)

breakdown_cov <- df_cov %>% 
  plyr::count('LIBVERORIG') %>% 
  transform(percent = scales::percent(freq / sum(freq)))

breakdown_cov <- breakdown_cov[rev(order(breakdown_cov$LIBVERORIG)),]
```

Row {data-height=200}
-------------------------------------

### Description

### evaluations with MF`r selected_MF` in `r params$LIBVER` {data-width=150}
```{r}
nEval <- df_cov %>% dplyr::select("MAT") %>% unique() %>% nrow()
nEvalTot <- df %>% subset(LIBVER==params$LIBVER) %>% select("MAT") %>% unique() %>% nrow()
gauge(nEval, min = 0, max = nEvalTot, gaugeSectors(
  success = c(0, 2), warning = c(3, 6), danger = c(7, 10)
))
```

### sections for MF`r selected_MF` in `r params$LIBVER` {data-width=150}
```{r}
flexdashboard::valueBox(nrow(df_cov), icon = "fa-file", href="../UniqueFiles/unique_origin.html")
# flexdashboard::valueBox(nrow(df_cov), icon = "fa-file", href="../UniqueFiles/unique_origin.html")
```

Row {data-height=800 .tabset .tabset-fade}
-------------------------------------
### Breakdown
```{r}
df_cov %>% 
  select(Z,X,A,M,MAT,MT,LIBVERORIG) %>%
  mutate(LIBVERORIG = paste0("<a href=","../UniqueFiles/unique_origin.html",">",LIBVERORIG,"</a>")
         ) %>%
  DT::datatable(rownames=FALSE,
                escape = F,
                colnames=c("ORIGIN" = 7),
                filter = 'top',
                options = list(
                  autowidth = F,
                  order = list(4, 'asc'),
                  pageLength = 12,
                  columnDefs = list(list(className = 'dt-center', targets = 0:6)),
                  sDom="rplt")
                )
```

### Bar Chart
```{r}
library(plotly)
plot_ly(breakdown_cov) %>%
  add_trace(x = ~LIBVERORIG, y = ~freq, type = 'bar',
            marker = list(color = my_colors))#%>%
            # textposition = 'inside',
            # textinfo = 'label+percent',
            # insidetextfont = list(color = '#FFFFFF'),
            # hoverinfo = 'text',
            # text = ~paste('$', LIBVERORIG, ' billions'),
            # marker = list(colors = my_colors,
            #               line = list(color = '#FFFFFF', width = 1)),
            # The 'pull' attribute can also be used to create space between the sectors
           # showlegend = F) %>%
  # layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
  #        yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```




Covariances
====
   
Other MF/MT Content
====