---
title: "Nuclear Data Mapping"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme : sandstone #readable #spacelab
    logo: logo.jpg
    #css: mystyles.css
params:
  SYMAMLIBVER: "U-238-g-JEFF-3.2"
  LIBVER2: "JEFF-3.1"
  
---
<style>                     
.navbar {
  background-color:white;
  border-color:gray;
}
.navbar-brand {
color:DarkSlateGray!important;
}
.dataTables_wrapper{
font-family: helvetica;
font-size: 11px; 
}
</style>  

```{r setup}
knitr::opts_chunk$set(echo = FALSE)
source('global.R')  
myparams<-strsplit(params$SYMAMLIBVER, "-")[[1]]
mX<-myparams[1]
mA<-myparams[2]
mM<-myparams[3]
mLIB<-myparams[4]
mVER<-myparams[5]

mSYMAM<-paste(mX,"-", mA,"-",mM, sep ="")
mLIBVER<-paste(mLIB,"-",mVER, sep = "")

output_dir<-paste(mLIB,mVER, sep = "")
output_file<-paste(mX,mA,mM)

```

Graph
=====================================  
 
Row {}
-------------------------------------
### {data-width=800}

###  {data-width=200}
```{r} 
flexdashboard::valueBox(mLIBVER, icon="fa-folder", href="https://www.oecd-nea.org", color=as.character(my_colors[mLIBVER]), caption = paste(" Release : ", libdates[mLIBVER]))

```   

Row {}
-------------------------------------

### MF, MT Mapping of ENDF6 file according to MF-MT Origin {data-height=2500}

```{r plotmap}
##plot_map : 
     
    pdf<-df%>%subset(X==mX & A==mA & M==mM & LIBVER==mLIBVER)
    
    title<-paste(mSYMAM," from ", mLIBVER)
    
    axisfont <- list(
      family = "Helvetica",
      size = 14,
      color = "blue"
    )
    
    yaxis=list(titlefont= axisfont)
    xaxis=list( 
      titlefont= axisfont,
      title = "MT",
      zeroline = FALSE,
      showline = FALSE,
      showticklabels = TRUE,
      showgrid = TRUE,
      tickangle=80
    )
    
    #changing column names for better readability in tooltip : 
    setnames(pdf, old=c("MFDES","MTDES", "LIBVERORIG"), new=c("Type","Reaction", "Matches"))
    
    g1<-ggplot(pdf, aes(x=MT, y=MF, Type=Type, Reaction=Reaction)) + 
      geom_tile(aes(fill=Matches)) +
      #geom_tile() +
      scale_y_discrete(drop=FALSE) + 
      scale_fill_manual(values=my_colors)+
      theme_light() + 
      theme(legend.title=element_blank(), 
            plot.background=element_rect(fill="white"), #can be 'darkseagreen' too...
            plot.margin = unit(c(0.7, 0, 2, 1), "cm")) #top, right, bottom, left
    p<-ggplotly(g1, width = 1200, 
                height = 500
                #tooltip = c("MF", "MFDES", "MT")
                )
    #print(g1)
    
    p%>%config(displayModeBar = 'pan',showLink=FALSE,senddata=FALSE,editable=FALSE,
                 displaylogo=FALSE, collaborate=FALSE, cloud=FALSE,
                 modeBarButtonsToRemove=c('select2d', 'lasso2d','hoverClosestCartesian',
                                          'hoverCompareCartesian'))%>%
      layout(title=title,
             autosize = F,
             yaxis=yaxis ,
             xaxis=xaxis ,
             showlegend = TRUE
             )
   p

```
   


Tables
=====================================  
 
Row {}
-------------------------------------
### {data-width=800}

 

###  {data-width=200}
```{r} 
flexdashboard::valueBox(mLIBVER, icon="fa-folder", href="https://www.oecd-nea.org", color=as.character(my_colors[mLIBVER]), caption = paste(" Release : ", libdates[mLIBVER]))

```   

Row {}
-------------------------------------

### Comparison of **different** data to other release (`r params$LIBVER2`)

```{r} 

  #pdf<-filter(df, X==mX, A==mA, M==mM)
  pdf<-df%>%subset(X==mX & A==mA & M==mM)
  
  lib1<-pdf%>%subset(LIBVER==mLIBVER)
  lib2<-pdf%>%subset(LIBVER==params$LIBVER2)
  
  lib1<-subset(lib1,select = c('MF', 'MFDES', 'MT', "MTDES", 'LIBVER', 'LIBVERORIG'))
  lib2<-subset(lib2,select = c('MF', 'MFDES', 'MT', "MTDES", 'LIBVER', 'LIBVERORIG'))
  comp<-merge(lib1, lib2, by = c('MF', 'MFDES', 'MT', "MTDES"))
  
  data.table::setnames(comp, old=c("LIBVERORIG.x","LIBVERORIG.y"), new=c("LIB1","LIB2"))
  data.table::setnames(comp, old=c("MFDES","MTDES"), new=c("MF TYPE","MT TYPE"))
  
  comp<-subset(comp, select = c('MF TYPE', 'MT TYPE', 'MF', 'MT', 'LIB1', 'LIB2'))
  
  #d<-filter(comp, LIB1!=LIB2) # diff occurrences 
  d<-comp%>%subset(LIB1!=LIB2) # diff occurrences 
  data.table::setnames(d, old=c("LIB1","LIB2"), new=c(mLIBVER,params$LIBVER2))
  datatable(d, filter='top', options = list(
    pageLength=50,
    rownames=FALSE,
    autowidth=FALSE,
    columnDefs=list(list(className='dt-center', targets=0:6))
    ))
  

```



   