Row {}
-------------------------------------

### {data-width=200}

```{r } 
flexdashboard::valueBox(mLIBVER, 
                        #icon="fa-folder-open-o", 
                        #href="https://www.oecd-nea.org",
                        #color=as.character(my_colors[mLIBVER]), 
                        color=libcolor,
                        caption = paste(" Released in ", libdates[mLIBVER]))

```   

### {data-width=160}

```{r } 
flexdashboard::valueBox(paste(params$X,params$A,params$M,sep='-'),
                        color=libcolor, 
                        caption = "Neutron File"
                        )

```   

### {data-width=128}

```{r } 
flexdashboard::valueBox(tot, color="Gainsboro", caption = "Sections in file")

```   

### {data-width=128}

```{r } 
flexdashboard::valueBox(totalupdated, color=UpdatedColor, href="#updated", caption = "Updated",
                        icon="fa-chevron-up")

```   

### {data-width=128}

```{r } 
flexdashboard::valueBox(newinlib1, color=NewColor,  href="#new", caption = "New", 
                        icon="fa-chevron-up")

```   

### {data-width=128}

```{r } 
flexdashboard::valueBox(totunchanged, color="LightGray",  href="#unchanged", caption = "Unchanged")

```   

### {data-width=128}

```{r } 
flexdashboard::valueBox(erasedfromlib2, color=ErasedColor,  href="#erased", caption = "Erased", 
                        icon="fa-chevron-down")

```   

Row {}
-------------------------------------


