
MF`r selected_MF`
=====================================
```{r}
df_cov <- subset(df, LIB==params$LIB & VER==params$VER & MF==selected_MF) %>%
  dplyr::arrange(Z, SYMA, M, MT)
```

Row
-------------------------------------

### Description{data-width=750}

MF `r selected_MF` : `r (mfs%>%subset(MF==selected_MF))$MFDES`. 

Showing `r paste(params$LIB,params$VER,sep='-')` distribution of data for MF `r selected_MF`, with matching origins for each MF/MT section. 
 
### Evaluations with MF `r selected_MF` in `r paste(params$LIB,params$VER,sep='-')` {data-width=250}
```{r}
nEval <- dplyr::select(df_cov, Z, A, M) %>% unique() %>% nrow()
nEvalTot <- df %>% subset(LIB==params$LIB & VER==params$VER, select=c(Z, A, M)) %>% unique() %>% nrow()
gauge(nEval, min = 0, max = nEvalTot, gaugeSectors(success = c(0, 10)))
```

<!-- This info is already given in the datatable -->
<!-- ### MF `r selected_MF` sections in `r paste(params$LIB,params$VER,sep='-')` {data-width=150} -->
<!-- ```{r} -->
<!-- flexdashboard::valueBox(nrow(df_cov), icon = "fa-file") -->

<!-- ``` -->

Row  
-------------------------------------
### List of `r paste(params$LIB,params$VER,sep='-')` isotopes containing MF `r selected_MF` data {data-width=750}
```{r}
df_cov %>%
  dplyr::select(Z, SYMA, M, MT, MTDES, LIBVERORIG) %>%
  data.table::setnames(
    old=c('Z','M',"SYMA","LIBVERORIG","MTDES"),
    new=c('Atomic number','Isomeric state',"Isotope","Matching", "Type of data")
    ) %>%
  DT::datatable(filter='top',
                rownames=FALSE,
                options = list(
                  pageLength=10,
                  lengthMenu=list(c(10, 50, 100, 200, 500, -1), list('10', '50', '100', '200', '500', 'All')),
                  autowidth=FALSE,
                  columnDefs=list(list(className='dt-center', targets=c(0:3,5)))
                  )
                )
```

### Origin histogram of MF `r selected_MF` sections found in `r paste(params$LIB,params$VER,sep='-')` {data-width=250}
```{r}
g <- ggplot(df %>% subset(LIB==params$LIB & VER==params$VER & MF==selected_MF), 
           aes(x = LIBVERORIG)) +
  scale_x_discrete(drop=FALSE) + 
  geom_histogram(stat = "count") +
  coord_flip() +
  guides(fill=FALSE) + #removes legend
  theme_light() +
  labs(y="Number of sections found", x="")

print(g)
# print(g)

```

