---
title: "Covariances"
author: "L. Fiorito and F. Michel-Sendis"
# date: "13 February 2018"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source: embed
params:
  RELEASE: "JEFF-3.3"
---

```{r setup, include=FALSE, cache=TRUE}
knitr::opts_chunk$set(echo = FALSE)
library(flexdashboard)
library(knitr)
library(dplyr)
source('global.R')
```


```{r}
selected_MF <- 31
```


MF`r selected_MF`
=====================================
```{r}
df_cov <- df %>%
  subset(LIBVER==params$RELEASE & MF==selected_MF)

breakdown_cov <- df_cov %>% 
  plyr::count('LIBVERORIG') %>% 
  transform(percent = scales::percent(freq / sum(freq)))

breakdown_cov <- breakdown_cov[rev(order(breakdown_cov$LIBVERORIG)),]
```

Row {data-height=200}
-------------------------------------

### Description

### evaluations with MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
nEval <- df_cov %>% select("MAT") %>% unique() %>% nrow()
nEvalTot <- df %>% subset(LIBVER==params$RELEASE) %>% select("MAT") %>% unique() %>% nrow()
gauge(nEval, min = 0, max = nEvalTot, gaugeSectors(
  success = c(0, 2), warning = c(3, 6), danger = c(7, 10)
))
```

### sections for MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
flexdashboard::valueBox(nrow(df_cov), icon = "fa-file", href="../UniqueFiles/unique_origin.html")
# flexdashboard::valueBox(nrow(df_cov), icon = "fa-file", href="../UniqueFiles/unique_origin.html")
```

Row {data-height=800 .tabset .tabset-fade}
-------------------------------------
### Breakdown
```{r}
df_cov %>% 
  select(Z,X,A,M,MAT,MT,LIBVERORIG) %>%
  mutate(LIBVERORIG = paste0("<a href=","../UniqueFiles/unique_origin.html",">",LIBVERORIG,"</a>")
         ) %>%
  DT::datatable(rownames=FALSE,
                escape = F,
                colnames=c("ORIGIN" = 7),
                filter = 'top',
                options = list(
                  autowidth = F,
                  order = list(4, 'asc'),
                  pageLength = 12,
                  columnDefs = list(list(className = 'dt-center', targets = 0:6)),
                  sDom="rplt")
                )
```

### Bar Chart
```{r}
library(plotly)
plot_ly(breakdown_cov) %>%
  add_trace(x = ~LIBVERORIG, y = ~freq, type = 'bar',
            marker = list(color = my_colors))#%>%
            # textposition = 'inside',
            # textinfo = 'label+percent',
            # insidetextfont = list(color = '#FFFFFF'),
            # hoverinfo = 'text',
            # text = ~paste('$', LIBVERORIG, ' billions'),
            # marker = list(colors = my_colors,
            #               line = list(color = '#FFFFFF', width = 1)),
            # The 'pull' attribute can also be used to create space between the sectors
           # showlegend = F) %>%
  # layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
  #        yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```

### Counts
```{r}
breakdown_cov %>% DT::datatable(rownames=FALSE,
                    colnames=c("ORIGIN","MF/MT COUNT","MF/MT PERCENT"),
                    options = list(
                      autowidth = F,
                      order = list(1, 'desc'),
                      pageLength = 100,
                      columnDefs = list(list(className = 'dt-center', targets = 0:2)),
                      sDom="rt")
                    )
```


```{r}
selected_MF <- 32
```


MF`r selected_MF`
=====================================
```{r}
df_cov <- df %>%
  subset(LIBVER==params$RELEASE & MF==selected_MF)

breakdown_cov <- df_cov %>% 
  plyr::count('LIBVERORIG') %>% 
  transform(percent = scales::percent(freq / sum(freq)))

breakdown_cov <- breakdown_cov[rev(order(breakdown_cov$LIBVERORIG)),]
```

Row {data-height=200}
-------------------------------------

### Description

### evaluations with MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
nEval <- df_cov %>% select("MAT") %>% unique() %>% nrow()
nEvalTot <- df %>% subset(LIBVER==params$RELEASE) %>% select("MAT") %>% unique() %>% nrow()
gauge(nEval, min = 0, max = nEvalTot, gaugeSectors(
  success = c(0, 2), warning = c(3, 6), danger = c(7, 10)
))
```

### sections for MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
flexdashboard::valueBox(nrow(df_cov), icon = "fa-file")
```

Row {data-height=800 .tabset .tabset-fade}
-------------------------------------
### Breakdown
```{r}
df_cov %>% 
  select(Z,X,A,M,MAT,MT,LIBVERORIG) %>%
  DT::datatable(rownames=FALSE,
                colnames=c("ORIGIN" = 7),
                filter = 'top',
                options = list(
                  autowidth = F,
                  order = list(4, 'asc'),
                  pageLength = 12,
                  columnDefs = list(list(className = 'dt-center', targets = 0:6)),
                  sDom="rplt")
                )
```

### Bar Chart
```{r}
library(plotly)
plot_ly(breakdown_cov) %>%
  add_trace(x = ~LIBVERORIG, y = ~freq, type = 'bar',
            marker = list(color = my_colors))#%>%
            # textposition = 'inside',
            # textinfo = 'label+percent',
            # insidetextfont = list(color = '#FFFFFF'),
            # hoverinfo = 'text',
            # text = ~paste('$', LIBVERORIG, ' billions'),
            # marker = list(colors = my_colors,
            #               line = list(color = '#FFFFFF', width = 1)),
            # The 'pull' attribute can also be used to create space between the sectors
           # showlegend = F) %>%
  # layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
  #        yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```

### Counts
```{r}
breakdown_cov %>% DT::datatable(rownames=FALSE,
                    colnames=c("ORIGIN","MF/MT COUNT","MF/MT PERCENT"),
                    options = list(
                      autowidth = F,
                      order = list(1, 'desc'),
                      pageLength = 100,
                      columnDefs = list(list(className = 'dt-center', targets = 0:2)),
                      sDom="rt")
                    )
```


```{r}
selected_MF <- 33
```


MF`r selected_MF`
=====================================
```{r}
df_cov <- df %>%
  subset(LIBVER==params$RELEASE & MF==selected_MF)

breakdown_cov <- df_cov %>% 
  plyr::count('LIBVERORIG') %>% 
  transform(percent = scales::percent(freq / sum(freq)))

breakdown_cov <- breakdown_cov[rev(order(breakdown_cov$LIBVERORIG)),]
```

Row {data-height=200}
-------------------------------------

### Description

### evaluations with MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
nEval <- df_cov %>% select("MAT") %>% unique() %>% nrow()
nEvalTot <- df %>% subset(LIBVER==params$RELEASE) %>% select("MAT") %>% unique() %>% nrow()
gauge(nEval, min = 0, max = nEvalTot, gaugeSectors(
  success = c(0, 2), warning = c(3, 6), danger = c(7, 10)
))
```

### sections for MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
flexdashboard::valueBox(nrow(df_cov), icon = "fa-file")
```

Row {data-height=800 .tabset .tabset-fade}
-------------------------------------
### Breakdown
```{r}
df_cov %>% 
  select(Z,X,A,M,MAT,MT,LIBVERORIG) %>%
  DT::datatable(rownames=FALSE,
                colnames=c("ORIGIN" = 7),
                filter = 'top',
                options = list(
                  autowidth = F,
                  order = list(4, 'asc'),
                  pageLength = 12,
                  columnDefs = list(list(className = 'dt-center', targets = 0:6)),
                  sDom="rplt")
                )
```

### Bar Chart
```{r}
library(plotly)
plot_ly(breakdown_cov) %>%
  add_trace(x = ~LIBVERORIG, y = ~freq, type = 'bar',
            marker = list(color = my_colors))#%>%
            # textposition = 'inside',
            # textinfo = 'label+percent',
            # insidetextfont = list(color = '#FFFFFF'),
            # hoverinfo = 'text',
            # text = ~paste('$', LIBVERORIG, ' billions'),
            # marker = list(colors = my_colors,
            #               line = list(color = '#FFFFFF', width = 1)),
            # The 'pull' attribute can also be used to create space between the sectors
           # showlegend = F) %>%
  # layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
  #        yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```

### Counts
```{r}
breakdown_cov %>% DT::datatable(rownames=FALSE,
                    colnames=c("ORIGIN","MF/MT COUNT","MF/MT PERCENT"),
                    options = list(
                      autowidth = F,
                      order = list(1, 'desc'),
                      pageLength = 100,
                      columnDefs = list(list(className = 'dt-center', targets = 0:2)),
                      sDom="rt")
                    )
```


```{r}
selected_MF <- 34
```


MF`r selected_MF`
=====================================
```{r}
df_cov <- df %>%
  subset(LIBVER==params$RELEASE & MF==selected_MF)

breakdown_cov <- df_cov %>% 
  plyr::count('LIBVERORIG') %>% 
  transform(percent = scales::percent(freq / sum(freq)))

breakdown_cov <- breakdown_cov[rev(order(breakdown_cov$LIBVERORIG)),]
```

Row {data-height=200}
-------------------------------------

### Description

### evaluations with MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
nEval <- df_cov %>% select("MAT") %>% unique() %>% nrow()
nEvalTot <- df %>% subset(LIBVER==params$RELEASE) %>% select("MAT") %>% unique() %>% nrow()
gauge(nEval, min = 0, max = nEvalTot, gaugeSectors(
  success = c(0, 2), warning = c(3, 6), danger = c(7, 10)
))
```

### sections for MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
flexdashboard::valueBox(nrow(df_cov), icon = "fa-file")
```

Row {data-height=800 .tabset .tabset-fade}
-------------------------------------
### Breakdown
```{r}
df_cov %>% 
  select(Z,X,A,M,MAT,MT,LIBVERORIG) %>%
  DT::datatable(rownames=FALSE,
                colnames=c("ORIGIN" = 7),
                filter = 'top',
                options = list(
                  autowidth = F,
                  order = list(4, 'asc'),
                  pageLength = 12,
                  columnDefs = list(list(className = 'dt-center', targets = 0:6)),
                  sDom="rplt")
                )
```

### Bar Chart
```{r}
library(plotly)
plot_ly(breakdown_cov) %>%
  add_trace(x = ~LIBVERORIG, y = ~freq, type = 'bar',
            marker = list(color = my_colors))#%>%
            # textposition = 'inside',
            # textinfo = 'label+percent',
            # insidetextfont = list(color = '#FFFFFF'),
            # hoverinfo = 'text',
            # text = ~paste('$', LIBVERORIG, ' billions'),
            # marker = list(colors = my_colors,
            #               line = list(color = '#FFFFFF', width = 1)),
            # The 'pull' attribute can also be used to create space between the sectors
           # showlegend = F) %>%
  # layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
  #        yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```

### Counts
```{r}
breakdown_cov %>% DT::datatable(rownames=FALSE,
                    colnames=c("ORIGIN","MF/MT COUNT","MF/MT PERCENT"),
                    options = list(
                      autowidth = F,
                      order = list(1, 'desc'),
                      pageLength = 100,
                      columnDefs = list(list(className = 'dt-center', targets = 0:2)),
                      sDom="rt")
                    )
```


```{r}
selected_MF <- 35
```


MF`r selected_MF`
=====================================
```{r}
df_cov <- df %>%
  subset(LIBVER==params$RELEASE & MF==selected_MF)

breakdown_cov <- df_cov %>% 
  plyr::count('LIBVERORIG') %>% 
  transform(percent = scales::percent(freq / sum(freq)))

breakdown_cov <- breakdown_cov[rev(order(breakdown_cov$LIBVERORIG)),]
```

Row {data-height=200}
-------------------------------------

### Description

### evaluations with MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
nEval <- df_cov %>% select("MAT") %>% unique() %>% nrow()
nEvalTot <- df %>% subset(LIBVER==params$RELEASE) %>% select("MAT") %>% unique() %>% nrow()
gauge(nEval, min = 0, max = nEvalTot, gaugeSectors(
  success = c(0, 2), warning = c(3, 6), danger = c(7, 10)
))
```

### sections for MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
flexdashboard::valueBox(nrow(df_cov), icon = "fa-file")
```

Row {data-height=800 .tabset .tabset-fade}
-------------------------------------
### Breakdown
```{r}
df_cov %>% 
  select(Z,X,A,M,MAT,MT,LIBVERORIG) %>%
  DT::datatable(rownames=FALSE,
                colnames=c("ORIGIN" = 7),
                filter = 'top',
                options = list(
                  autowidth = F,
                  order = list(4, 'asc'),
                  pageLength = 12,
                  columnDefs = list(list(className = 'dt-center', targets = 0:6)),
                  sDom="rplt")
                )
```

### Bar Chart
```{r}
library(plotly)
plot_ly(breakdown_cov) %>%
  add_trace(x = ~LIBVERORIG, y = ~freq, type = 'bar',
            marker = list(color = my_colors))#%>%
            # textposition = 'inside',
            # textinfo = 'label+percent',
            # insidetextfont = list(color = '#FFFFFF'),
            # hoverinfo = 'text',
            # text = ~paste('$', LIBVERORIG, ' billions'),
            # marker = list(colors = my_colors,
            #               line = list(color = '#FFFFFF', width = 1)),
            # The 'pull' attribute can also be used to create space between the sectors
           # showlegend = F) %>%
  # layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
  #        yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```

### Counts
```{r}
breakdown_cov %>% DT::datatable(rownames=FALSE,
                    colnames=c("ORIGIN","MF/MT COUNT","MF/MT PERCENT"),
                    options = list(
                      autowidth = F,
                      order = list(1, 'desc'),
                      pageLength = 100,
                      columnDefs = list(list(className = 'dt-center', targets = 0:2)),
                      sDom="rt")
                    )
```


```{r}
selected_MF <- 40
```


MF`r selected_MF`
=====================================
```{r}
df_cov <- df %>%
  subset(LIBVER==params$RELEASE & MF==selected_MF)

breakdown_cov <- df_cov %>% 
  plyr::count('LIBVERORIG') %>% 
  transform(percent = scales::percent(freq / sum(freq)))

breakdown_cov <- breakdown_cov[rev(order(breakdown_cov$LIBVERORIG)),]
```

Row {data-height=200}
-------------------------------------

### Description

### evaluations with MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
nEval <- df_cov %>% select("MAT") %>% unique() %>% nrow()
nEvalTot <- df %>% subset(LIBVER==params$RELEASE) %>% select("MAT") %>% unique() %>% nrow()
gauge(nEval, min = 0, max = nEvalTot, gaugeSectors(
  success = c(0, 2), warning = c(3, 6), danger = c(7, 10)
))
```

### sections for MF`r selected_MF` in `r params$RELEASE` {data-width=150}
```{r}
flexdashboard::valueBox(nrow(df_cov), icon = "fa-file")
```

Row {data-height=800 .tabset .tabset-fade}
-------------------------------------
### Breakdown
```{r}
df_cov %>% 
  select(Z,X,A,M,MAT,MT,LIBVERORIG) %>%
  DT::datatable(rownames=FALSE,
                colnames=c("ORIGIN" = 7),
                filter = 'top',
                options = list(
                  autowidth = F,
                  order = list(4, 'asc'),
                  pageLength = 12,
                  columnDefs = list(list(className = 'dt-center', targets = 0:6)),
                  sDom="rplt")
                )
```

### Bar Chart
```{r}
library(plotly)
plot_ly(breakdown_cov) %>%
  add_trace(x = ~LIBVERORIG, y = ~freq, type = 'bar',
            marker = list(color = my_colors))#%>%
            # textposition = 'inside',
            # textinfo = 'label+percent',
            # insidetextfont = list(color = '#FFFFFF'),
            # hoverinfo = 'text',
            # text = ~paste('$', LIBVERORIG, ' billions'),
            # marker = list(colors = my_colors,
            #               line = list(color = '#FFFFFF', width = 1)),
            # The 'pull' attribute can also be used to create space between the sectors
           # showlegend = F) %>%
  # layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
  #        yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```

### Counts
```{r}
breakdown_cov %>% DT::datatable(rownames=FALSE,
                    colnames=c("ORIGIN","MF/MT COUNT","MF/MT PERCENT"),
                    options = list(
                      autowidth = F,
                      order = list(1, 'desc'),
                      pageLength = 100,
                      columnDefs = list(list(className = 'dt-center', targets = 0:2)),
                      sDom="rt")
                    )
```
